# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Creasy
subtitle: spiral out. keep going.
author: Brian J. Creasy
email: genetik@caffeine.nu
description: The personal website of a human named Brian Creasy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.briancreasy.com"

# code paths
source: .
destination: _site
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

# site paths
root: /

# Handling Reading
safe: false # safe mode: if true, disable plugins and ignore symlinks
include:
  - ".htaccess"
  - ".well-known"
exclude: []
keep_files:
  - ".git"
  - ".svn"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
show_drafts: null
limit_posts: 0
future: false
unpublished: false

# Plugins
whitelist: []
gems:
  - jekyll-paginate

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /log/:year/:month/:day/:title/
paginate_path: /page:num
timezone: America/Chicago
locale: en_US
paginate: 5
pagination_dir: log
category_dir: log/categories
date_format: "%F %T"
excerpt_link: "Read on &rarr;"
titlecase: true
